[package]
name = "bank_account"
version = "0.1.0"
edition = "2021"

[dependencies]
thalo = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true, features = ["derive"] }
wit-bindgen = "0.15"
