branch_whitelist = ["main"]

pre_bump_hooks = [
  "./scripts/bump.sh {{latest}} {{version}}",
  "cargo build --workspace --release",
]

post_bump_hooks = ["git push", "git push origin {{version}}"]

[changelog]
path = "CHANGELOG.md"
template = "remote"
remote = "github.com"
repository = "thalo"
owner = "thalo-rs"
authors = [{ signature = "Ari Seyhun", username = "tqwewe" }]
