[package]
name = "thalo"
version = "0.6.0"
edition = "2021"

[dependencies]
heck = "0.4.1"
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
thalo_derive = { workspace = true }
thiserror = { workspace = true }
wit-bindgen = "0.13"
