[package]
name = "thalo_runtime"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "thalo"
path = "./src/main.rs"

[dependencies]
thalo = { workspace = true, features = ["consumer"] }
thalo_registry = { workspace = true }

anyhow = { workspace = true }
bytes = { workspace = true }
chrono = { workspace = true }
clap = { workspace = true }
derive_more = { workspace = true }
directories-next = { workspace = true }
esdl = { workspace = true }
futures = { workspace = true }
host = { git = "https://github.com/bytecodealliance/preview2-prototyping" }
message_db = { workspace = true }
quinn = { workspace = true }
rand = "0.8.5"
rcgen = { version = "0.10.0", features = ["pem", "x509-parser"] }
rmp-serde = { workspace = true }
rustls = { workspace = true }
rustls-pemfile = "1.0.1"
semver = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "sync"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
wasi-common = { git = "https://github.com/bytecodealliance/preview2-prototyping" }
wasmtime = { git = "https://github.com/bytecodealliance/wasmtime", features = [
  "component-model",
] }
